### ISSUE TITLE
Does this support transparent GIFs?

### ISSUE THREAD

**Issue by teddis** [felipecsl/GifImageView#11]
I'm rendering animated GIFs with transparent backgrounds. They appear correctly on iOS but on Android they have a black background. Am I not specifying a parameter for the decoder? I didn't see one. Looks like it's taking its cue from each frame. Thanks!

**Comment by ed-george** [comment]
As this isn't resolved but is presumably a feature request, should this issue be re-opened?

**Comment by felipecsl** [comment]
agreed. it is definitely a feature request

**Comment by wulaoh** [comment]
please use 'Bitmap.Config.ARGB_8888' to replace 'Bitmap.Config.RGB_565'
