### ISSUE TITLE
Bitmap to ByteArray

### ISSUE THREAD

**Issue by aritraroy** [felipecsl/GifImageView#17]
I have a Bitmap containing the entire GIF and all its frames. How can I convert it into a byte array to be used in setBytes method.

**Comment by felipecsl** [comment]
This doesnt make much sense. A GIF is composed of several Bitmaps. You can't have a GIF that's a Bitmap, unless the GIF only has a single frame.

**Comment by aritraroy** [comment]
Then how do I attach GIFs in this View. I mean if I have an image in the internal memory, how do I attach it to the View? Any help is really appreciated.

**Comment by felipecsl** [comment]
Ultimately all you need is a byte array. If you have a File for example, you need to read that file into a byte[] and then set into the GifImageView. The sample project in the repository has an example for downloading the GIF from the network and displaying. Where is your file coming from? Is it already in the device?

**Comment by aritraroy** [comment]
Yes, it is in the device.

**Comment by felipecsl** [comment]
http://stackoverflow.com/questions/6058003/elegant-way-to-read-file-into-byte-array-in-java

**Comment by aritraroy** [comment]
Works perfectly for me now. Thanks for your help.

And btw, if there some best practice to make minimum memory usage? I mean should I be stopping the animations on onStop()? Or something else?

**Comment by felipecsl** [comment]
yeah i'd recommend stopping the animation when you leave the activity

**Comment by aritraroy** [comment]
That's exactly what I did. Thanks.
