### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by thest1** [felipecsl/GifImageView#27]
CleanupRunnable is never involved in your implementation. Please take a look carefully. There's a call in the beginning of the Thread, not much usefull. But if I'm inside for() loop and clear() method is called is doesn't invoke cleanupRunnable. That causes a pretty annoying memory leak. Makes sense? Easy to fix but I need your review.

**Comment by felipecsl** [comment]
Sure, PRs always welcome

**Comment by felipecsl** [comment]
Fixed via #28
