### ISSUE TITLE
divide by zero Problem

### ISSUE THREAD

**Issue by TaQuangTien** [felipecsl/GifImageView#29]
I get this error when using GifImageView with GridView using custom ImageAdapter extends BaseAdapter

12-02 16:06:56.619 15491-15601/? E/AndroidRuntime: FATAL EXCEPTION: Thread-3008
                                                   Process: vn.messengerkvtm.gs, PID: 15491
                                                   java.lang.ArithmeticException: divide by zero
                                                       at com.felipecsl.gifimageview.library.GifDecoder.advance(GifDecoder.java:229)
                                                       at com.felipecsl.gifimageview.library.GifImageView.run(GifImageView.java:157)
                                                       at java.lang.Thread.run(Thread.java:841)

[ImageAdapter.txt](https://github.com/felipecsl/GifImageView/files/49510/ImageAdapter.txt)

**Comment by felipecsl** [comment]
can you also please attach the GIF image that you're using?

**Comment by TaQuangTien** [comment]
![received_10208002856299538](https://cloud.githubusercontent.com/assets/4410820/11539468/c4d62a9c-9959-11e5-908e-cf50a21ac0e9.gif)

Here is one of my images. I created it by png images using Easy Gif Animator.

**Comment by shtil** [comment]
Hmm.. I have this exception too...

**Comment by luciofm** [comment]
This is the Glide commit  that fixed the issue
https://github.com/bumptech/glide/commit/5ce0c1172e076cd72af8efbde97cffca5f215ba1

**Comment by rafalzawadzki** [comment]
Happens to me too, irregularly.

**Comment by andrewlord1990** [comment]
Fixed by #36.
