### ISSUE TITLE
How to animate gif?

### ISSUE THREAD

**Issue by jskcse4** [felipecsl/GifImageView#31]
I have gif image in various drawables folder. How to animate my gif image.

**Comment by felipecsl** [comment]
GifImageView expects a byte array (`byte[]`) for a GIF file. If you have a list of drawables (that could be converted to bitmaps) you could encode them as a GIF yourself or just animate them manually by displaying one at a time every few milliseconds. That's not a GIF though, and this library wouldn't help you with that.
