### ISSUE TITLE
Loading gif image from local resources

### ISSUE THREAD

**Issue by smtabatabaie** [felipecsl/GifImageView#33]
Hi , I wanted to ask if it is possible to load a gif image from local resources like raw folder.
Thanks

**Comment by felipecsl** [comment]
This has been already asked here #12

**Comment by smtabatabaie** [comment]
Thanks very much , so another problem which occurred for me with also ion happened with gifimageview. My gif plays with missing parts , this is the gif I'm using http://i.imgur.com/xB97bYI.gif
I'll appreciate if you can help me with this.
Thanks
