### ISSUE TITLE
Latest commit on gradle available?

### ISSUE THREAD

**Issue by SalmanJawed** [felipecsl/GifImageView#42]
Can we get the latest code update i.e. fix of divide by zero error through gradle?

I am using
compile 'com.felipecsl:gifimageview:2.0.0'
to use this library but it is still showing divide by zero exception.

Please help!!

**Comment by felipecsl** [comment]
I'll upload a snapshot of latest master tonight!

**Comment by SalmanJawed** [comment]
Thanks a lot for your co-operation. Will I be able to use the latest commit through the same gradle line or will the version number be updated?

**Comment by felipecsl** [comment]
You'll need to use a new version number. Likely `2.0.1-SNAPSHOT`

**Comment by SalmanJawed** [comment]
Ok thanks (y). Please comment after updating. Great work by the way :)

**Comment by SalmanJawed** [comment]
Any updates?

**Comment by felipecsl** [comment]
Done, it's available [here](https://oss.sonatype.org/content/repositories/snapshots/com/felipecsl/gifimageview/2.1.0-SNAPSHOT/)
