### ISSUE TITLE
First frame is overlapped over last frame on tranparent animated GIF

### ISSUE THREAD

**Issue by lhoracek** [felipecsl/GifImageView#46]
I have looping transparent GIF and when the loop restarts, first frame is displayed over last frame from the sequence.

**Comment by lhoracek** [comment]
I made OnFrameAvailable listener and i do processing the frames to have alternating color background and then the single frame drawn there. The last frame contains both of the images. Can there be any problem with DISPOSAL_PREVIOUS for the last / first frame progression. It is displayed correctly in browser, mac preview etc. It is mostly trasparent animated gif so the two frames are visible as overlayed

**Comment by keewon** [comment]
Could you share your GIF? I had similar problem with following image,
![cat](https://cloud.githubusercontent.com/assets/227190/21489571/83e43ea2-cc2f-11e6-83d9-fd913dbdf99e.gif)

and it looks like working well after following patch. (GifDecoder.java)
![2016-12-27 12 23 54](https://cloud.githubusercontent.com/assets/227190/21489575/93261138-cc2f-11e6-8557-39439ae4a4da.png)

I just want to know my code is right.

**Comment by lhoracek** [comment]
Unfortunately I can't share the original picture, but I will try finding or creating some that has similar issue. That that seems to be the right fix.

**Comment by keewon** [comment]
Thanks for confirmation. I'll submit a PR.
