### ISSUE TITLE
Does this support Android 4.4.2?

### ISSUE THREAD

**Issue by chengxinwen-vinci** [felipecsl/GifImageView#52]
I use setImageResource() to set a gif from drawable folder, not download from url. And call startAnimation(), then isAnimating() return true, but UI doesn't visually work.

**Comment by felipecsl** [comment]
Yep it works, but you have to call `setBytes()` instead

**Comment by chengxinwen-vinci** [comment]
Hi @felipecsl , I'm not sure how to setBytes() for a local resource, would you please give me a hint? Thanks!

**Comment by felipecsl** [comment]
See #12
