### ISSUE TITLE
No resetAnimation()

### ISSUE THREAD

**Issue by jaychang0917** [felipecsl/GifImageView#60]
It seems there is no such meethod in the latest release.

**Comment by felipecsl** [comment]
That is still unreleased. You can use it with version `2.2.0-SNAPSHOT`

**Comment by jaychang0917** [comment]
It shows `Failed to resolve: com.felipecsl:gifimageview:2.2.0-SNAPSHOT`

**Comment by felipecsl** [comment]
do you have `maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }` in your gradle repositories list?
