### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LloydFinch** [felipecsl/GifImageView#69]
gifimageview.GifDecoder.getNextFrame()' on a null object reference
	at com.game_werewolf.voice.gifimageview.GifImageView.run(GifImageView.java:179)
	at java.lang.Thread.run(Thread.java:818)

**Comment by felipecsl** [comment]
Can you please attach an example GIF image to help reproduce this issue? Also which Android version are you using?

**Comment by felipecsl** [comment]
Closed due to inactivity
