### ISSUE TITLE
How to display gif image from external storage ?

### ISSUE THREAD

**Issue by ervinod** [felipecsl/GifImageView#72]
Hello there,

I am unable to display locally stored gif image programatically.
Here is my code
String root = Environment.getExternalStorageDirectory().toString()+"/EnthuonsChat/Images/"+imageName;
                        File fileToDownload = new File(root);
                        if(fileToDownload.exists()){
                            new GifDataDownloader() {
                                @Override
                                protected void onPostExecute(final byte[] bytes) {
                                    ((ItemMessageUserHolder) holder).gifImageView.setBytes(bytes);
                                    ((ItemMessageUserHolder) holder).gifImageView.startAnimation();
                                }
                            }.execute(root);
                        }
Please help me to resolve this issue....

**Comment by Crashdummyy** [comment]
Did you put StartAnimation as well ?
Mine won't display if I don't start the Animation as well

**Comment by felipecsl** [comment]
You're likely loading the file incorrectly. make sure it its correctly loaded before calling `setBytes` and `startAnimation`
