### ISSUE TITLE
getting Build failed after migrated to AndroidX 

### ISSUE THREAD

**Issue by shyamkumarm** [felipecsl/GifImageView#74]
**Build error:**
ERROR: Unable to resolve dependency for ':app@devDebug/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@devDebugAndroidTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@devDebugUnitTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@devRelease/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@devReleaseUnitTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@inhouseDebug/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@inhouseDebugAndroidTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@inhouseDebugUnitTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@inhouseRelease/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@inhouseReleaseUnitTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@betaDebug/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@betaDebugAndroidTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@betaDebugUnitTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@betaRelease/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@betaReleaseUnitTest/compileClasspath': Failed to transform file 'gifimageview-2.2.0.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

**Comment by rascalyen** [comment]
@shyamkumarm Did you have any solution that other than downgrading from AndroidX ?

**Comment by d-ahrens** [comment]
Jetify is working with the 2.2.0-SNAPSHOT
add the repository:
maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
use the following version:
implementation 'com.felipecsl:gifimageview:2.2.0-SNAPSHOT'

**Comment by NullByte08** [comment]
> Jetify is working with the 2.2.0-SNAPSHOT
> add the repository:
> maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
> use the following version:
> implementation 'com.felipecsl:gifimageview:2.2.0-SNAPSHOT'

It is not being resolved: `Failed to resolve: com.felipecsl:gifimageview:2.2.0-SNAPSHOT`

**Comment by OlegKrell** [comment]
@NullByte08 change implementation 'com.felipecsl:gifimageview:2.2.0-SNAPSHOT'   to implementation 'com.felipecsl:gifimageview:2.3.0-SNAPSHOT' and it will be working
